from cx_Freeze import setup, Executable

hidden_imports = [
    "MunicipiosPR.AnaliseAlmiranteTamandare",
    "MunicipiosPR.AnaliseAndira",
    "MunicipiosPR.AnaliseApucarana",
    "MunicipiosPR.AnaliseArapongas",
    "MunicipiosPR.AnaliseArapoti",
    "MunicipiosPR.AnaliseBarbosaFerraz",
    "MunicipiosPR.AnaliseBelaVistaDoParaiso",
    "MunicipiosPR.AnaliseBoaVenturaDeSaoRoque",
    "MunicipiosPR.AnaliseBorrazopolis",
    "MunicipiosPR.AnaliseCampinaGrandeDoSul",
    "MunicipiosPR.AnaliseCampoDoTenente",
    "MunicipiosPR.AnaliseCampoLargo",
    "MunicipiosPR.AnaliseCampoMourao",
    "MunicipiosPR.AnaliseCascavel",
    "MunicipiosPR.AnaliseChopinzinho",
    "MunicipiosPR.AnaliseClevelandia",
    "MunicipiosPR.AnaliseColorado",
    "MunicipiosPR.AnaliseCruzeiroDoOeste",
    "MunicipiosPR.AnaliseDoisVizinhos",
    "MunicipiosPR.AnaliseDoutorCamargo",
    "MunicipiosPR.AnaliseFigueira",
    "MunicipiosPR.AnaliseFranciscoBeltrao",
    "MunicipiosPR.AnaliseGoioere",
    "MunicipiosPR.AnaliseGuaira",
    "MunicipiosPR.AnaliseGuaraci",
    "MunicipiosPR.AnaliseGuarapuava",
    "MunicipiosPR.AnaliseIbaiti",
    "MunicipiosPR.AnaliseIbipora",
    "MunicipiosPR.AnaliseImbau",
    "MunicipiosPR.AnaliseIretama",
    "MunicipiosPR.AnaliseItambe",
    "MunicipiosPR.AnaliseItapejaraDoeste",
    "MunicipiosPR.AnaliseIvaipora",
    "MunicipiosPR.AnaliseIzabelDoOeste",
    "MunicipiosPR.AnaliseJaniopolis",
    "MunicipiosPR.AnaliseJapura",
    "MunicipiosPR.AnaliseJardimAlegre",
    "MunicipiosPR.AnaliseJoaquimTavora",
    "MunicipiosPR.AnaliseJussara",
    "MunicipiosPR.AnaliseLapa",
    "MunicipiosPR.AnaliseLaranjeirasDoSul",
    "MunicipiosPR.AnaliseLondrina",
    "MunicipiosPR.AnaliseLuiziana",
    "MunicipiosPR.AnaliseLunardelli",
    "MunicipiosPR.AnaliseMandaguaçu",
    "MunicipiosPR.AnaliseMandaguari",
    "MunicipiosPR.AnaliseMandirituba",
    "MunicipiosPR.AnaliseMarechalCandidoRondon",
    "MunicipiosPR.AnaliseMarilandiaDoSul",
    "MunicipiosPR.AnaliseMariluz",
    "MunicipiosPR.AnaliseMaringa",
    "MunicipiosPR.AnaliseMarquinho",
    "MunicipiosPR.AnaliseMatinhos",
    "MunicipiosPR.AnaliseNovaLondrina",
    "MunicipiosPR.AnaliseNovaOlimpia",
    "MunicipiosPR.AnaliseNovasLaranjeiras",
    "MunicipiosPR.AnaliseOuroVerdeDoOeste",
    "MunicipiosPR.AnalisePalmital",
    "MunicipiosPR.AnaliseParaisoDoNorte",
    "MunicipiosPR.AnaliseParanagua",
    "MunicipiosPR.AnalisePauloFrontin",
    "MunicipiosPR.AnalisePeabiru",
    "MunicipiosPR.AnalisePerobal",
    "MunicipiosPR.AnalisePiraiDoSul",
    "MunicipiosPR.AnalisePlanalto",
    "MunicipiosPR.AnalisePontaGrossa",
    "MunicipiosPR.AnaliseRibeiraoClaro",
    "MunicipiosPR.AnaliseRibeiraoDoPinhal",
    "MunicipiosPR.AnaliseRioAzul",
    "MunicipiosPR.AnaliseSantaFe",
    "MunicipiosPR.AnaliseSantaHelena",
    "MunicipiosPR.AnaliseSantaIsabelDoIvai",
    "MunicipiosPR.AnaliseSantoAntonioDoSudoeste",
    "MunicipiosPR.AnaliseSaoJoaoDoIvai",
    "MunicipiosPR.AnaliseSaoJoseDosPinhais",
    "MunicipiosPR.AnaliseSaoManoel",
    "MunicipiosPR.AnaliseSiqueiraCampos",
    "MunicipiosPR.AnaliseTerraBoa",
    "MunicipiosPR.AnaliseToledo",
    "MunicipiosPR.AnaliseUniaoDaVitoria",
    "MunicipiosPR.AnaliseVirmond",
    "MunicipiosPR.AnaliseVitorino"
]

build_exe_options = {
    "packages": ["fitz", "xlsxwriter", "google_auth_oauthlib", "googleapiclient", "gspread", "webview"],
    "excludes": [],
    "include_files": [
        'D:/AutomacaoFapec/Professor formador/credenciais_google.json',
        ('D:/AutomacaoFapec/Professor formador/interface/index.html', 'interface/index.html'),
        ('D:/AutomacaoFapec/Professor formador/interface/src/css/mensagens.css', 'interface/src/css/mensagens.css'),
        ('D:/AutomacaoFapec/Professor formador/interface/src/css/navegacaoBorda.css', 'interface/src/css/navegacaoBorda.css'),
        ('D:/AutomacaoFapec/Professor formador/interface/src/css/nexus.css', 'interface/src/css/nexus.css'),
        ('D:/AutomacaoFapec/Professor formador/interface/src/css/reset.css', 'interface/src/css/reset.css'),
        ('D:/AutomacaoFapec/Professor formador/interface/src/imagens/Fapec-logo.png', 'interface/src/imagens/Fapec-logo.png'),
        ('D:/AutomacaoFapec/Professor formador/interface/src/js/index.js', 'interface/src/js/index.js')
        ],
    "includes": hidden_imports
}

setup(
    name="Análise de certidões negativas de débitos",
    version="4.0",
    description="Análise de certidões negativas de débitos.",
    options={"build_exe": build_exe_options},
    executables=[Executable("AnaliseCertidoes.py", base="Win32GUI")]
)